name: Deploy

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [16]
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: ["amd64", "arm64"]

    env:
      BUILD_VIBE_FROM_SOURCE: true

    steps:
      - name: Use Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
  
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install npm packages
        run: npm install --build-from-source --no-package-lock

      - name: Deploy
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.node"
          draft: false
          prerelease: true
          token: ${{ secrets.PREBUILD_GITHUB_TOKEN }}
